import { Component, type ErrorInfo, type FormEvent, type ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { catalog } from "./data";
import { applyCartCommand, closestProducts, formatMoney, isParsedCommand, itemSubtotalPaise, loadData, localizedResponse, makeItem, mergeItem, parseCommand, pluralUnit, rankSubstitutes, recommendProducts, searchProducts, serializeData, suggestions } from "./domain";
import type { Activity, AppData, ParsedCommand, Product, ShoppingItem, Source } from "./types";
import { createRecognition, resolveRecognitionLocale, shouldExecuteFinal, speechSupported, type VoiceState } from "./voice";
import productSprite from "./assets/grocery-sprite.webp";
import productSpriteNuts from "./assets/grocery-sprite-nuts.webp";

const STORE="voice-cart-v1";
const categories=["Produce","Dairy","Bakery","Grains & Flours","Pulses","Spices","Dry Fruits & Nuts","Cooking Essentials","Beverages","Snacks","Frozen","Household","Personal Care","Other Food","Other"];
const labels:Record<VoiceState,string>={idle:"Tap to speak",requesting:"Requesting access",listening:"Listening…",processing:"Processing…",success:"Done",error:"Try again",unsupported:"Voice unavailable"};
const commandExamples=["Add 50 grams of almonds","Add two pieces of coconut","Remove 2 packets of milk","Milk kitna hai?","Tell me my entire list","Find toothpaste under Rs 100","What is the cost of toothbrush?","Recommend fruits under ₹200","Clear my list","Undo"];

class ErrorBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}componentDidCatch(error:Error,info:ErrorInfo){console.error(error,info)}render(){return this.state.failed?<main className="fatal"><h1>Piko needs a refresh</h1><p>Your locally saved list is safe. Reload the page to continue.</p><button onClick={()=>location.reload()}>Reload</button></main>:this.props.children}}

function ProductPhoto({product}:{product:Product}){const [failed,setFailed]=useState(false),x=product.photoIndex%6,y=Math.floor(product.photoIndex/6),newSheet=product.photoSheet===1;return failed?<div className="product-photo fallback" role="img" aria-label={`${product.name} product photograph unavailable`}>{product.name.slice(0,1)}</div>:<div className="product-photo"><img src={newSheet?productSpriteNuts:productSprite} alt={`${product.name} product photograph`} loading="lazy" width="1200" height="1200" style={{"--photo-x":x,"--photo-y":y,"--photo-rows":newSheet?3:6} as React.CSSProperties} onError={()=>setFailed(true)}/></div>}
function TourTip({title,text,action,onAction,onClose}:{title:string;text:string;action:string;onAction:()=>void;onClose:()=>void}){return <section className="tour-tip" role="dialog" aria-label={title}><button className="tour-close" onClick={onClose} aria-label="Exit guide">×</button><strong>{title}</strong><p>{text}</p><div><button onClick={onAction}>{action}</button></div></section>}

function App(){
  const [data,setData]=useState<AppData>(()=>loadData(localStorage.getItem(STORE)));
  const [tab,setTab]=useState("list"); const [language,setLanguage]=useState("auto"); const [voiceState,setVoiceState]=useState<VoiceState>(()=>speechSupported()?"idle":"unsupported");
  const [transcript,setTranscript]=useState(""); const [message,setMessage]=useState("Say or type a command to get started."); const [command,setCommand]=useState("");
  const [results,setResults]=useState<Product[]>([]); const [pending,setPending]=useState<ParsedCommand|null>(null); const [help,setHelp]=useState(false); const [speechSettings,setSpeechSettings]=useState(false); const [tourStep,setTourStep]=useState<"start"|"help"|"speech"|"download"|"theme"|"language"|null>("start");
  const [dark,setDark]=useState(()=>localStorage.getItem("voice-cart-theme")==="dark");
  const recognition=useRef<ReturnType<typeof createRecognition>>(null); const recognitionActive=useRef(false); const voiceSession=useRef(0); const undo=useRef<AppData|null>(null); const lastItem=useRef<string|undefined>(undefined); const lastFinal=useRef({text:"",at:0});
  useEffect(()=>localStorage.setItem(STORE,serializeData(data)),[data]);
  useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("voice-cart-theme",dark?"dark":"light")},[dark]);
  useEffect(()=>()=>{voiceSession.current++;const current=recognition.current;current?.cancelTimeout();if(current&&recognitionActive.current)current.abort();recognition.current=null;recognitionActive.current=false},[]);
  const stats=useMemo(()=>{const totalPaise=data.list.reduce((n,x)=>n+itemSubtotalPaise(x),0),savingsPaise=data.list.reduce((n,x)=>n+Math.max(0,Math.round(((x.originalUnitPricePaise??x.estimatedUnitPricePaise??0)-(x.estimatedUnitPricePaise??0))*x.quantity)),0);return{unique:data.list.length,total:data.list.reduce((n,x)=>n+x.quantity,0),totalPaise,savingsPaise}},[data.list]);
  const smart=useMemo(()=>suggestions(data),[data]);
  const announce=(text:string,user:string,action:string,kind:Activity["kind"]="success")=>{setMessage(text);setData(d=>({...d,activity:[{id:crypto.randomUUID(),user,action,assistant:text,at:new Date().toISOString(),kind},...d.activity].slice(0,8)}));if(data.speechEnabled&&"speechSynthesis"in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}};
  const preserve=()=>{undo.current=data};
  const addProduct=(p:Product,source:Source="manual",quantity=1,unit=p.unit,responseLanguage="en")=>{const item=makeItem(p.name,quantity,unit,source,p);lastItem.current=item.normalizedName;setData(d=>({...d,list:mergeItem(d.list,item)}));setTab("list");announce(localizedResponse(responseLanguage,"added",{quantity,unit:pluralUnit(item.unit,quantity),name:p.name}),p.name,"ADD_ITEM")};
  const addGeneric=(p:ParsedCommand,source:Source)=>{if(!p.normalizedItem||!p.item)return;const item=makeItem(p.item,p.quantity??1,p.unit??"",source);lastItem.current=item.normalizedName;setData(d=>({...d,list:mergeItem(d.list,item)}));announce(`${localizedResponse(p.language,"added",{quantity:item.quantity,unit:pluralUnit(item.unit,item.quantity),name:item.name})} Estimated subtotal ${formatMoney(itemSubtotalPaise(item))}.`,p.rawTranscript,"ADD_ITEM")};
  const undoLast=()=>{if(!undo.current){announce("There is nothing to undo.","Undo","UNDO","info");return}setData(undo.current);undo.current=null;announce("Undid the last cart action.","Undo","UNDO")};
  const listText=()=>`Piko shopping list\n${data.list.map(x=>`${x.quantity} ${pluralUnit(x.unit,x.quantity)} ${x.name} — ${formatMoney(itemSubtotalPaise(x))}`).join("\n")}\nEstimated total: ${formatMoney(stats.totalPaise)}\nIndia average estimates, updated August 2026.`;
  const shareList=async()=>{const text=listText();try{if(navigator.share)await navigator.share({title:"Piko shopping list",text});else{await navigator.clipboard.writeText(text);announce("List copied to the clipboard.","Share this list","SHARE_LIST")}}catch{announce("Sharing was cancelled. You can use Print / PDF instead.","Share this list","SHARE_LIST","info")}};
  const downloadImage=()=>{const lines=listText().split("\n"),canvas=document.createElement("canvas");canvas.width=1080;canvas.height=220+lines.length*48;const ctx=canvas.getContext("2d")!;ctx.fillStyle="#fff8f6";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#443025";ctx.font="700 42px system-ui";lines.forEach((line,i)=>ctx.fillText(line,60,80+i*48));canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="piko-list.png";a.click();URL.revokeObjectURL(a.href)},"image/png")};

  const execute=(value:unknown,source:Source)=>{
    if(!isParsedCommand(value)){setMessage("Ignored an invalid structured command. Your cart was not changed.");return}
    const p=value;
    const q=p.quantity??1;
    const itemRequired=["ADD_ITEM","REMOVE_QUANTITY","REMOVE_ALL","SET_QUANTITY","QUERY_QUANTITY","SEARCH_PRODUCT"].includes(p.intent);
    const mutating=["ADD_ITEM","REMOVE_QUANTITY","REMOVE_ALL","SET_QUANTITY","CLEAR_LIST","CHOOSE_PRODUCT"].includes(p.intent);
    if(p.intent==="UNKNOWN"){announce(p.needsConfirmation&&p.normalizedItem==="garnish"?"Do you want garnish recommendations, or should I add a custom item named Garnish?":`I didn’t understand “${p.rawTranscript}”. Try asking about your list, naming a food, or saying what you want to change.`,p.rawTranscript,"UNKNOWN","info");return}
    if(p.intent==="QUERY_QUANTITY"&&p.needsConfirmation){setPending(p);announce(`Did you want the quantity of ${p.item} in your cart, or information about its quality?`,p.rawTranscript,p.intent,"info");return}
    if(p.confidence<.6&&!mutating){announce(`I’m not confident I understood “${p.rawTranscript}”. Please rephrase or edit it; your cart was not changed.`,p.rawTranscript,p.intent,"info");return}
    if(p.confidence<.6||itemRequired&&!p.normalizedItem&&!p.items?.length){setPending(p);announce(`I’m not confident about “${p.rawTranscript}”. Confirm, edit, retry, or cancel.`,p.rawTranscript,"UNKNOWN","info");return}
    if(p.intent==="ADD_ITEM"&&p.items&&p.items.length>1){preserve();const made=p.items.map(part=>{const matches=catalog.filter(x=>x.normalizedName===part.normalizedItem&&x.inStock),product=matches.length===1?matches[0]:undefined;return makeItem(product?.name??part.item,part.quantity,part.unit,source,product)});lastItem.current=made.at(-1)?.normalizedName;setData(d=>({...d,list:made.reduce(mergeItem,d.list)}));setTab("list");announce(localizedResponse(p.language,"added",{quantity:made.reduce((n,x)=>n+x.quantity,0),unit:"items",name:made.map(x=>x.name).join(", ")}),p.rawTranscript,p.intent);return}
    if(p.intent==="ADD_ITEM"){preserve();const exact=searchProducts(p);if(exact.length)addProduct(exact[0],source,q,p.unit||exact[0].unit,p.language);else addGeneric(p,source);return}
    if(["REMOVE_QUANTITY","REMOVE_ALL","SET_QUANTITY","QUERY_QUANTITY","QUERY_LIST"].includes(p.intent)){const contextual=p.normalizedItem==="it"?{...p,normalizedItem:lastItem.current}:p,result=applyCartCommand(data.list,contextual);if(result.needsConfirmation){setPending(contextual);announce(result.message,p.rawTranscript,p.intent,"info");return}if(result.changed){preserve();setData(d=>({...d,list:result.list}))}if(contextual.normalizedItem)lastItem.current=contextual.normalizedItem;if(p.intent==="QUERY_LIST")setTab("list");announce(result.message,p.rawTranscript,p.intent,result.changed||p.intent.startsWith("QUERY")?"success":"error");return}
    if(p.intent==="RECOMMEND_PRODUCTS"){const found=recommendProducts(p,data);setResults(found);setTab("search");announce(found.length?localizedResponse(p.language,"recommend",{count:found.length}):"I couldn’t find a matching recommendation.",p.rawTranscript,p.intent,found.length?"success":"error");return}
    if(p.intent==="SEARCH_PRODUCT"||p.intent==="SHOW_SUBSTITUTES"){const name=p.normalizedItem??lastItem.current,matched=p.intent==="SEARCH_PRODUCT"?searchProducts(p):rankSubstitutes(catalog.find(x=>x.normalizedName===name)??catalog[0],p.attributes?.[0]),found=matched.length?matched:p.intent==="SEARCH_PRODUCT"?closestProducts(p):[];setResults(found);setTab("search");announce(matched.length?`I found ${matched.length} matching product${matched.length>1?"s":""}, sorted by estimated price.`:found.length?"No product matched that price range. I’m showing the closest catalog options; nothing was added.":"No products matched. Try fewer filters.",p.rawTranscript,p.intent,matched.length?"success":"info");return}
    if(p.intent==="CHOOSE_PRODUCT"){const chosen=/cheaper/i.test(p.rawTranscript)?[...results].sort((a,b)=>a.price-b.price)[0]:p.selectionIndex!==undefined?results[p.selectionIndex]:undefined;if(chosen){preserve();addProduct(chosen,source,1,chosen.unit,p.language)}else announce("I couldn’t match that choice. Tap a product or say its position.",p.rawTranscript,p.intent,"error");return}
    if(p.intent==="CART_TOTAL"){announce(`Your estimated cart total is ${formatMoney(stats.totalPaise)}${stats.savingsPaise?`, saving ${formatMoney(stats.savingsPaise)}`:""}.`,p.rawTranscript,p.intent);return}
    if(p.intent==="PRICE_QUERY"){const products=(p.normalizedItem?catalog.filter(x=>x.normalizedName===p.normalizedItem&&x.inStock):results).sort((a,b)=>a.price-b.price);setResults(products);if(products.length)setTab("search");const cheapest=products[0],highest=products.at(-1);announce(products.length>1?`${cheapest.name} options range from ${formatMoney(cheapest.price*100)} to ${formatMoney((highest?.price??cheapest.price)*100)}. The cheapest is ${cheapest.brand} ${cheapest.size} at an estimated ${formatMoney(cheapest.price*100)}.`:cheapest?`${cheapest.brand} ${cheapest.name}, ${cheapest.size}, is estimated at ${formatMoney(cheapest.price*100)}.`:"I couldn’t find that product in the sample catalog.",p.rawTranscript,p.intent,products.length?"success":"error");return}
    if(p.intent==="COMPARE_PRODUCTS"){const products=(p.items??[]).flatMap(item=>catalog.filter(x=>x.normalizedName===item.normalizedItem&&x.inStock)).sort((a,b)=>a.price-b.price);setResults(products);setTab("search");announce(products.length?`${products[0].brand} ${products[0].name} is the cheapest match at ${formatMoney(products[0].price*100)}. Compare the displayed sizes and attributes before choosing.`:"Name the products you want to compare.",p.rawTranscript,p.intent,products.length?"success":"info");return}
    if(p.intent==="NAVIGATE"&&p.targetTab){setTab(p.targetTab);announce(`Opened ${p.targetTab==="search"?"Discover":p.targetTab}.`,p.rawTranscript,p.intent);return}
    if(p.intent==="UNDO"){undoLast();return}
    if(p.intent==="SHARE_LIST"){void shareList();return}
    if(p.intent==="CLEAR_LIST"){if(!data.list.length){announce("Your shopping list is already empty.",p.rawTranscript,p.intent,"info");return}setPending(p);setMessage("Clear your full list? This can be undone.")}
  };
  const submit=(e:FormEvent)=>{e.preventDefault();const value=command.trim();if(!value)return;setTranscript(value);setCommand("");execute(parseCommand(value),"text")};
  const startVoice=()=>{
    if(recognition.current){voiceSession.current++;const current=recognition.current;current.cancelTimeout();recognition.current=null;if(recognitionActive.current)current.abort();recognitionActive.current=false;setVoiceState("idle");setMessage("Listening stopped.");return}
    if(!speechSupported()){setVoiceState("unsupported");setMessage("Voice recognition is not supported in this browser.");return}
    const session=++voiceSession.current,active=()=>session===voiceSession.current;
    setVoiceState("requesting");setMessage("Starting the microphone…");setTranscript("");
    const r=createRecognition(resolveRecognitionLocale(language,navigator.language),{
      cartProductNames:data.list.map(x=>x.normalizedName),
      onState:s=>{if(!active())return;setVoiceState(s);if(s==="listening"){recognitionActive.current=true;setMessage("Listening… Speak now.")}if(s==="processing")setMessage("Processing your command…");if(s==="idle"){recognitionActive.current=false;recognition.current=null}},
      onActivity:kind=>{if(active())setMessage(kind==="speech"?"Speech detected…":"Microphone active. Listening…")},
      onTranscript:(text,final,confidence)=>{if(!active())return;setTranscript(text);if(final){const normalized=parseCommand(text),selectedLanguage=language==="auto"?normalized.language:language.split("-")[0],key=normalized.normalizedTranscript??text,decision=shouldExecuteFinal(lastFinal.current,key);lastFinal.current=decision.marker;if(!decision.execute)return;execute({...normalized,language:selectedLanguage,confidence:Math.min(normalized.confidence,confidence||normalized.confidence)},"voice")}},
      onError:text=>{if(active())setMessage(text)}
    });
    if(!r){setVoiceState("unsupported");setMessage("Voice recognition is unavailable in this browser. Type your command below.");return}
    recognition.current=r;
    try{r.start();recognitionActive.current=true;void navigator.mediaDevices?.enumerateDevices().then(devices=>{if(active()&&recognition.current===r&&!devices.some(device=>device.kind==="audioinput")){r.cancelTimeout();voiceSession.current++;recognition.current=null;recognitionActive.current=false;r.abort();setVoiceState("error");setMessage("No microphone was found.")}})}catch(error){r.cancelTimeout();voiceSession.current++;recognition.current=null;recognitionActive.current=false;setVoiceState("error");setMessage(error instanceof DOMException&&error.name==="InvalidStateError"?"Voice recognition was already active. Please retry.":"The microphone could not start. Please retry.")}
  };
  const updateItem=(id:string,patch:Partial<ShoppingItem>)=>setData(d=>({...d,list:d.list.map(x=>x.id===id?{...x,...patch,quantity:Math.max(.01,Number(patch.quantity??x.quantity)),updatedAt:new Date().toISOString()}:x)}));
  const remove=(id:string)=>{preserve();setData(d=>({...d,list:d.list.filter(x=>x.id!==id)}));setMessage("Item removed. Undo is available.")};
  const completePurchased=()=>{const bought=data.list.filter(x=>x.purchased);if(!bought.length)return;preserve();const purchasedAt=new Date().toISOString();setData(d=>({...d,list:d.list.filter(x=>!x.purchased),history:[...bought.map(x=>({...x,purchasedAt})),...d.history]}));announce(`Moved ${bought.length} purchased item${bought.length>1?"s":""} to history.`,"Touch action","COMPLETE_PURCHASE")};
  return <ErrorBoundary><div className="app">
    {tourStep&&<div className="tour-shade" aria-hidden="true"/>}
    <header><a className="brand" href="#top" aria-label="Piko home"><span>P</span>Piko</a><div className="header-actions">
      <span className={`tour-anchor tour-language ${tourStep==="language"?"active":""}`}><select aria-label="Voice language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="auto">Auto detect</option><option value="en-IN">English / Hinglish</option><option value="hi-IN">हिन्दी / Hinglish</option><option value="bn-IN">বাংলা</option><option value="mr-IN">मराठी</option><option value="gu-IN">ગુજરાતી</option><option value="pa-IN">ਪੰਜਾਬੀ</option><option value="ta-IN">தமிழ்</option><option value="te-IN">తెలుగు</option><option value="kn-IN">ಕನ್ನಡ</option><option value="ml-IN">മലയാളം</option><option value="ur-IN">اردو</option></select>{tourStep==="language"&&<TourTip title="Choose your language" text="Use Auto detect or select the language you plan to speak." action="Finish" onAction={()=>setTourStep(null)} onClose={()=>setTourStep(null)}/>}</span>
      <span className={`tour-anchor ${tourStep==="theme"?"active":""}`}><button className="icon" onClick={()=>setDark(x=>!x)} aria-label={`Use ${dark?"light":"dark"} theme`}>{dark?"☀":"☾"}</button>{tourStep==="theme"&&<TourTip title="Light and dark mode" text="Use this icon to switch Piko’s appearance." action="Next" onAction={()=>setTourStep("language")} onClose={()=>setTourStep(null)}/>}</span>
      <span className={`tour-anchor ${tourStep==="download"?"active":""}`}><button className="icon" onClick={downloadImage} aria-label="Download list as image">⇩</button>{tourStep==="download"&&<TourTip title="Download PNG" text="Save your current shopping list as an image." action="Next" onAction={()=>setTourStep("theme")} onClose={()=>setTourStep(null)}/>}</span>
      <span className={`tour-anchor ${tourStep==="speech"?"active":""}`}><button className="icon" onClick={()=>setSpeechSettings(true)} aria-label="Speak confirmations aloud" aria-pressed={data.speechEnabled} title={`Spoken confirmations ${data.speechEnabled?"on":"off"}`}>{data.speechEnabled?"🔊":"🔇"}</button>{tourStep==="speech"&&<TourTip title="Speak confirmations aloud" text="Choose whether Piko reads confirmations and answers aloud." action="Next" onAction={()=>{setSpeechSettings(false);setTourStep("download")}} onClose={()=>{setSpeechSettings(false);setTourStep(null)}}/>}</span>
      <span className={`tour-anchor ${tourStep==="start"||tourStep==="help"?"active":""}`}><button className="icon" onClick={()=>setHelp(true)} aria-label="Help">?</button>{tourStep==="start"&&<TourTip title="Welcome to Piko" text="Take a quick tour of the controls and commands." action="Start guide" onAction={()=>{setHelp(true);setTourStep("help")}} onClose={()=>setTourStep(null)}/>} {tourStep==="help"&&<TourTip title="Use these commands" text="These examples show the natural shopping requests Piko understands." action="Next" onAction={()=>{setHelp(false);setSpeechSettings(true);setTourStep("speech")}} onClose={()=>{setHelp(false);setTourStep(null)}}/>}</span>
    </div></header>
    <section id="top" className="hero" aria-labelledby="hero-title"><div><p className="eyebrow">LOCAL-FIRST SHOPPING</p><h1 id="hero-title">What do you need?</h1><p>Speak naturally. Auto detect supports English and major Indian-language grocery terms.</p></div><button className={`mic ${voiceState}`} onClick={startVoice} aria-label={voiceState==="listening"?"Stop listening":"Start voice command"} aria-pressed={voiceState==="listening"}><span aria-hidden="true">{voiceState==="listening"?"■":"●"}</span>{labels[voiceState]}</button></section>
    {!speechSupported()&&<p className="warning" role="status">Voice recognition isn’t supported here. Use the text command below; Chromium-based browsers work best.</p>}
    <section className="command-card" aria-live="polite"><div><span>YOU SAID</span><strong>{transcript||"Your transcript will appear here"}</strong></div><p>{message}</p><form onSubmit={submit}><label className="sr-only" htmlFor="command">Type a command</label><input id="command" value={command} onChange={e=>setCommand(e.target.value)} placeholder="Try “Add 2 bottles of water”"/><button>Send</button></form></section>
    <nav className="tabs" aria-label="Main sections">{[["list","Shopping list"],["search","Discover"],["history","Activity"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}{id==="list"&&data.list.length>0?<b>{data.list.length}</b>:null}</button>)}</nav>
    <main>{tab==="list"&&<ListView/>}{tab==="search"&&<SearchView/>}{tab==="history"&&<HistoryView/>}</main>
    <button className="floating-mic" onClick={startVoice} aria-label="Start voice command">●</button>
    {pending&&<div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">Check that command</h2><p>“{pending.rawTranscript}”</p><p className="muted">{message}</p><div className="modal-actions">{pending.intent==="CLEAR_LIST"?<button className="danger" onClick={()=>{preserve();setData(d=>({...d,list:[]}));setPending(null);setMessage("Shopping list cleared. Undo is available.")}}>Clear list</button>:<button onClick={()=>{const p={...pending,confidence:1,needsConfirmation:false};setPending(null);execute(p,"text")}}>Confirm</button>}<button onClick={()=>{setCommand(pending.rawTranscript);setPending(null);document.getElementById("command")?.focus()}}>Edit</button><button onClick={()=>{setPending(null);startVoice()}}>Retry</button><button className="secondary" onClick={()=>setPending(null)}>Cancel</button></div></section></div>}
    {help&&<div className="modal-backdrop"><section className="modal help" role="dialog" aria-modal="true" aria-labelledby="help-guide-title"><button className="close" onClick={()=>{setHelp(false);if(tourStep==="help")setTourStep(null)}} aria-label="Close commands">×</button><h2 id="help-guide-title">Commands that work</h2><ul>{commandExamples.map(example=><li key={example}>{example}</li>)}</ul></section></div>}
    {speechSettings&&<div className="modal-backdrop"><section className="modal speech-guide" role="dialog" aria-modal="true" aria-labelledby="speech-guide-title"><button className="close" onClick={()=>{setSpeechSettings(false);if(tourStep==="speech")setTourStep(null)}} aria-label="Close spoken confirmations">×</button><div className="guide-symbol" aria-hidden="true">{data.speechEnabled?"🔊":"🔇"}</div><h2 id="speech-guide-title">Speak confirmations aloud</h2><p>Turn this on when you want Piko to read action confirmations and answers aloud using your browser’s voice output.</p><label className="speech-setting"><input type="checkbox" checked={data.speechEnabled} onChange={e=>setData(d=>({...d,speechEnabled:e.target.checked}))}/> Speak confirmations aloud</label><p className="muted">This controls voice output only. It does not change microphone input or store audio.</p><div className="modal-actions"><button onClick={()=>setSpeechSettings(false)}>Done</button></div></section></div>}
  </div></ErrorBoundary>;

  function ListView(){const grouped=categories.map(c=>[c,data.list.filter(x=>x.category===c)] as const).filter(([,items])=>items.length);return <div className="layout"><section><div className="section-head"><div><p className="eyebrow">YOUR BASKET</p><h2>Shopping list</h2></div><div className="list-actions">{undo.current&&<button className="secondary" onClick={undoLast}>Undo</button>}<button className="secondary" onClick={()=>void shareList()}>Share</button><button className="secondary" onClick={()=>window.print()}>Print / PDF</button></div></div><div className="stats"><span><b>{stats.unique}</b> unique</span><span><b>{stats.total}</b> total qty</span><span><b>{formatMoney(stats.savingsPaise)}</b> savings</span><span><b>{formatMoney(stats.totalPaise)}</b> estimated total</span></div>{!data.list.length?<Empty title="Your list is ready" text="Add an item with your voice, the command box, or Discover."/>:grouped.map(([category,items])=><section className="group" key={category}><h3>{category}</h3>{items.map(item=><article className={`item ${item.purchased?"purchased":""}`} key={item.id}><input type="checkbox" checked={item.purchased} onChange={e=>updateItem(item.id,{purchased:e.target.checked})} aria-label={`Mark ${item.name} purchased`}/><div className="item-main"><strong>{item.name}</strong>{item.brand&&<small>{item.brand}{item.size?` · ${item.size}`:""}</small>}<span>{item.quantity} {item.unit} · {item.approximatePrice?"Approx.":"Estimated"} {formatMoney(item.estimatedUnitPricePaise??0)} / {item.unit} · subtotal {formatMoney(itemSubtotalPaise(item))}</span>{item.originalUnitPricePaise&&<span>Estimated discount {formatMoney(item.originalUnitPricePaise-(item.estimatedUnitPricePaise??0))} / {item.unit}</span>}<details><summary>Edit details</summary><div className="edit-grid"><label>Name<input value={item.name} onChange={e=>updateItem(item.id,{name:e.target.value})}/></label><label>Unit<input value={item.unit} onChange={e=>updateItem(item.id,{unit:e.target.value})}/></label></div></details></div><div className="stepper"><button onClick={()=>updateItem(item.id,{quantity:item.quantity-1})} aria-label={`Decrease ${item.name}`}>−</button><input aria-label={`${item.name} quantity`} type="number" min="0.01" step="0.01" value={item.quantity} onChange={e=>updateItem(item.id,{quantity:Number(e.target.value)})}/><button onClick={()=>updateItem(item.id,{quantity:item.quantity+1})} aria-label={`Increase ${item.name}`}>+</button></div><div className="row-actions"><button className="delete" onClick={()=>remove(item.id)} aria-label={`Remove ${item.name}`}>×</button></div></article>)}</section>)}{data.list.some(x=>x.purchased)&&<button className="wide" onClick={completePurchased}>Move purchased to history</button>}<p className="muted">India average catalog estimates, updated August 2026. Not live retailer prices.</p></section><Suggestions/></div>}
  function SearchView(){const [query,setQuery]=useState("");const shown=results.length?results:catalog.filter(p=>`${p.name} ${p.brand} ${p.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));return <section><div className="section-head"><div><p className="eyebrow">SAMPLE LOCAL CATALOG</p><h2>Discover products</h2></div></div><input className="search" placeholder="Search name, brand, or attribute" value={query} onChange={e=>{setQuery(e.target.value);setResults([])}}/><p className="muted">Prices and stock are illustrative, not live retailer data.</p><div className="product-grid">{shown.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!shown.length&&<Empty title="No products found" text="Try removing a size, attribute, or price filter."/>}</section>}
  function ProductCard({product:p}:{product:Product}){const inCart=data.list.find(x=>x.productId===p.id),reason=p.onSale?"On sale in the sample catalog.":p.tags.some(x=>["healthy","fruit","protein","whole-wheat","gluten-free"].includes(x))?`Useful ${p.tags.find(x=>["healthy","fruit","protein","whole-wheat","gluten-free"].includes(x))} option.`:`Available ${p.category.toLowerCase()} option.`;return <article className="product"><ProductPhoto product={p}/><span className={`stock ${p.inStock?"":"out"}`}>{p.inStock?"In stock":"Unavailable"}</span><h3>{p.name}</h3><p><b>{p.brand}</b> · {p.size}</p><p>{p.category} · {reason}</p><strong>{formatMoney(p.price*100)} {p.onSale&&<><del>{formatMoney((p.originalPrice??p.price)*100)}</del> <small>{Math.round((1-p.price/(p.originalPrice??p.price))*100)}% off</small></>}</strong><div>{p.inStock?(inCart?<div className="stepper"><button onClick={()=>updateItem(inCart.id,{quantity:inCart.quantity-1})} aria-label={`Decrease ${p.brand} ${p.name}`}>−</button><span>{inCart.quantity}</span><button onClick={()=>updateItem(inCart.id,{quantity:inCart.quantity+1})} aria-label={`Increase ${p.brand} ${p.name}`}>+</button></div>:<button onClick={()=>addProduct(p)}>Add to list</button>):<button onClick={()=>setResults(rankSubstitutes(p))}>See substitutes</button>}</div></article>}
  function Suggestions(){return <aside><div className="section-head"><div><p className="eyebrow">EXPLAINABLE PICKS</p><h2>Smart suggestions</h2></div></div>{smart.length?smart.map(s=><article className="suggestion" key={s.id}><span>{s.kind}</span><h3>{s.title}</h3><p>{s.reason}</p><div><button onClick={()=>addProduct(s.product,"suggestion")}>Add</button><button className="secondary" onClick={()=>setData(d=>({...d,dismissed:[...d.dismissed,s.id]}))}>Dismiss</button></div></article>):<p className="muted">Suggestions appear from repeat purchases, seasonality, or sample sales.</p>}</aside>}
  function HistoryView(){return <section><div className="section-head"><div><p className="eyebrow">LOCAL RECORD</p><h2>History & activity</h2></div>{(data.history.length||data.activity.length)?<button className="secondary" onClick={()=>{if(confirm("Clear shopping history and recent activity?"))setData(d=>({...d,history:[],activity:[]}))}}>Clear data</button>:null}</div><div className="history-layout"><div><h3>Purchases</h3>{data.history.length?data.history.map(x=><article className="history-row" key={`${x.id}-${x.purchasedAt}`}><div><strong>{x.name}</strong><span>{x.quantity} {x.unit} · {x.category}</span></div><time>{new Date(x.purchasedAt).toLocaleDateString()}</time></article>):<p className="muted">Completed items will appear here.</p>}</div><div><h3>Recent conversation</h3>{data.activity.map(a=><article className="activity" key={a.id}><span className={a.kind}>{a.action.replaceAll("_"," ")}</span><p><b>You:</b> {a.user}</p><p><b>Assistant:</b> {a.assistant}</p></article>)}</div></div></section>}
}

function Empty({title,text}:{title:string;text:string}){return <div className="empty"><div aria-hidden="true">◎</div><h3>{title}</h3><p>{text}</p></div>}
export default App;
