import type { Category, Product } from "./types";

const p=(id:string,name:string,normalizedName:string,brand:string,category:Category,size:string,unit:string,price:number,photoIndex:number,tags:string[]=[],extra:Partial<Product>={}):Product=>({id,name,normalizedName,brand,category,size,unit,price,photoIndex,tags,inStock:true,...extra});

export const catalog:Product[]=[
  p("mother-milk","Milk","milk","Mother Dairy","Dairy","1 L","l",56,0,["toned"],{substituteIds:["sofit-almond","amul-milk"]}),
  p("amul-milk","Milk","milk","Amul","Dairy","1 L","l",58,0,["toned"],{substituteIds:["mother-milk","sofit-almond"]}),
  p("sofit-almond","Almond milk","almond milk","Sofit","Dairy","1 L","l",295,1,["vegan","lactose-free"],{substituteIds:["mother-milk"]}),
  p("farm-eggs","Eggs","egg","Farm Fresh","Dairy","6 pieces","piece",72,2,["protein"]),
  p("harvest-bread","Bread","bread","Harvest Gold","Bakery","450 g","packet",55,3,["whole-wheat"],{substituteIds:["brown-bread"]}),
  p("brown-bread","Brown bread","brown bread","Britannia","Bakery","400 g","packet",50,4,["whole-wheat","healthy"],{substituteIds:["harvest-bread"]}),
  p("tata-salt","Salt","salt","Tata Salt","Cooking Essentials","1 kg","packet",28,5,["iodized"]),
  p("madhur-sugar","Sugar","sugar","Madhur","Cooking Essentials","1 kg","packet",54,6),
  p("aashirvaad-atta","Atta / Whole Wheat Flour","atta","Aashirvaad","Grains & Flours","5 kg","kg",285,7,["whole-wheat"]),
  p("fresh-atta","Atta / Whole Wheat Flour","atta","Fresh Mills","Grains & Flours","1 kg","kg",62,7,["whole-wheat"]),
  p("fresh-maida","Maida","maida","Fresh Mills","Grains & Flours","1 kg","kg",68,8,["all-purpose-flour"]),
  p("fresh-besan","Besan","besan","Fresh Mills","Grains & Flours","1 kg","kg",95,9,["gram-flour","protein","gluten-free"]),
  p("india-rice","Basmati rice","rice","India Gate","Grains & Flours","5 kg","kg",640,10,["basmati"]),
  p("bajra","Bajra","bajra","Fresh Mills","Grains & Flours","1 kg","kg",65,11,["whole-grain","gluten-free"]),
  p("fortune-oil","Cooking oil","cooking oil","Fortune","Cooking Essentials","1 L","bottle",148,12,["sunflower"],{onSale:true,originalPrice:170}),
  p("pepsodent-toothpaste","Toothpaste","toothpaste","Pepsodent","Personal Care","100 g","piece",85,13,["cavity-care"]),
  p("dabur-toothpaste","Toothpaste","toothpaste","Dabur Red","Personal Care","200 g","piece",118,13,["herbal"],{onSale:true,originalPrice:135}),
  p("colgate-toothpaste","Toothpaste","toothpaste","Colgate","Personal Care","150 g","piece",145,13,["cavity-care"]),
  p("sensodyne-toothpaste","Toothpaste","toothpaste","Sensodyne","Personal Care","100 g","piece",210,13,["sensitive"]),
  p("oralb-brush","Toothbrush","toothbrush","Oral-B","Personal Care","1 piece","piece",25,14,["soft"]),
  p("colgate-brush","Toothbrush","toothbrush","Colgate","Personal Care","1 piece","piece",55,14,["medium"]),
  p("sensodyne-brush","Toothbrush","toothbrush","Sensodyne","Personal Care","2 pieces","piece",120,14,["soft"]),
  p("apple","Apples","apple","Fresh","Produce","1 kg","kg",180,15,["fruit","healthy"],{seasonalMonths:[7,8,9,10]}),
  p("banana","Bananas","banana","Fresh","Produce","6 pieces","piece",55,16,["fruit"],{seasonalMonths:[1,2,3,4,5,6,7,8,9,10,11,12]}),
  p("orange","Oranges","orange","Fresh","Produce","1 piece","piece",20,17,["fruit","vitamin-c"],{seasonalMonths:[11,12,1,2]}),
  p("mango","Mangoes","mango","Fresh","Produce","1 kg","kg",160,18,["fruit"],{seasonalMonths:[4,5,6,7]}),
  p("tomato","Tomatoes","tomato","Fresh","Produce","1 kg","kg",48,19,["vegetable"]),
  p("onion","Onions","onion","Fresh","Produce","1 kg","kg",40,20,["vegetable","healthy"]),
  p("spinach","Spinach","spinach","Fresh","Produce","1 bunch","bunch",30,21,["vegetable","healthy","iron"]),
  p("potato","Potatoes","potato","Fresh","Produce","1 kg","kg",35,22,["vegetable"]),
  p("coriander-leaves","Fresh coriander leaves","coriander","Fresh","Produce","1 bunch","bunch",25,23,["dhaniya","fresh","herb"]),
  p("coriander-seeds","Coriander seeds","coriander","Fresh Mills","Spices","100 g","packet",30,24,["dhaniya","seeds"]),
  p("coriander-powder","Coriander powder","coriander","Everest","Spices","100 g","packet",42,25,["dhaniya","powder"]),
  p("water","Water","water","Bisleri","Beverages","1 L","bottle",20,26),
  p("chips","Potato chips","chips","Lay's","Snacks","90 g","packet",50,27,["snack"]),
  p("dishwash","Dishwash liquid","dishwash liquid","Vim","Household","500 ml","bottle",115,28,["cleaning"]),
  p("amul-butter","Butter","butter","Amul","Dairy","500 g","packet",285,29,["dairy"],{substituteIds:["nutralite","peanut-butter"]}),
  p("nutralite","Table spread","table spread","Nutralite","Dairy","500 g","packet",210,30,["lower-cost"],{substituteIds:["amul-butter"]}),
  p("peanut-butter","Peanut butter","peanut butter","Pintola","Cooking Essentials","350 g","jar",199,31,["high-protein","vegan"],{substituteIds:["amul-butter"]}),
  p("olive-oil","Olive oil","olive oil","Figaro","Cooking Essentials","1 L","bottle",799,32,["healthy"]),
  p("ice-cream","Ice cream","ice cream","Amul","Frozen","750 ml","tub",240,33,["dessert"]),
  p("green-tea","Green tea","green tea","Lipton","Beverages","25 bags","box",165,34,["healthy","sugar-free"]),
  p("coconut-milk","Coconut milk","coconut milk","Dabur Hommade","Cooking Essentials","200 ml","can",85,35,["vegan","lactose-free"],{substituteIds:["sofit-almond"]}),
  p("almonds","Almonds","almond","Fresh Mills","Dry Fruits & Nuts","100 g","g",95,0,["healthy","protein"],{photoSheet:1,aliases:["almond","almonds","badam","badaam","बादाम","কাঠবাদাম","બદામ","ਬਦਾਮ","பாதாம்","బాదం","ಬಾದಾಮಿ","ബദാം","بادام"]}),
  p("fox-nuts","Fox Nuts","fox nut","Fresh Mills","Dry Fruits & Nuts","100 g","g",110,1,["healthy","snack"],{photoSheet:1,aliases:["fox nut","fox nuts","makhana","makhane","मखाना","मखाने","মাখানা","મખાણા","ਮਖਾਣੇ","மக்கானா","మఖానా","ಮಖಾನಾ","മഖാന","مکھانے"]}),
  p("cashews","Cashews","cashew","Fresh Mills","Dry Fruits & Nuts","100 g","g",105,2,["healthy","protein"],{photoSheet:1,aliases:["cashew","cashews","cashew nut","cashew nuts","kaju","kaaju","काजू","কাজু","કાજુ","ਕਾਜੂ","முந்திரி","జీడిపప్పు","ಗೋಡಂಬಿ","കശുവണ്ടി","کاجو"]}),
  p("lemon","Lemon","lemon","Fresh","Produce","1 piece","piece",8,3,["fruit","vitamin-c"],{photoSheet:1,aliases:["lemon","lemons","nimbu","neembu","नींबू","निम्बू","लिंबू","লেবু","લીંબુ","ਨਿੰਬੂ","எலுமிச்சை","నిమ్మకాయ","ನಿಂಬೆ","നാരങ്ങ","لیموں"]}),
  p("coconut","Coconut","coconut","Fresh","Produce","1 piece","piece",45,4,["fruit","fresh"],{photoSheet:1,aliases:["coconut","coconuts","nariyal","नारियल","नारळ","নারকেল","નાળિયેર","ਨਾਰੀਅਲ","தேங்காய்","కొబ్బరికాయ","ತೆಂಗಿನಕಾಯಿ","തേങ്ങ","ناریل"]}),
  p("mint","Mint","mint","Fresh","Produce","1 bunch","bunch",20,5,["fresh","herb"],{photoSheet:1,aliases:["mint","pudina","पुदीना","পুদিনা","ફુદીનો","ਪੁਦੀਨਾ","புதினா","పుదీనా","ಪುದೀನಾ","പുതിന","پودینہ"]}),
  p("ginger","Ginger","ginger","Fresh","Produce","100 g","g",30,6,["fresh","spice"],{photoSheet:1,aliases:["ginger","adrak","अदरक","आले","আদা","આદુ","ਅਦਰਕ","இஞ்சி","అల్లం","ಶುಂಠಿ","ഇഞ്ചി","ادرک"]}),
  p("garlic","Garlic","garlic","Fresh","Produce","100 g","g",35,7,["fresh","spice"],{photoSheet:1,aliases:["garlic","lahsun","lehsun","लहसुन","लसूण","রসুন","લસણ","ਲਸਣ","பூண்டு","వెల్లుల్లి","ಬೆಳ್ಳುಳ್ಳಿ","വെളുത്തുള്ളി","لہسن"]}),
  p("green-chilli","Green Chilli","green chilli","Fresh","Produce","100 g","g",20,8,["fresh","spice"],{photoSheet:1,aliases:["green chilli","green chillies","hari mirch","हरी मिर्च","हिरवी मिरची","কাঁচা মরিচ","લીલું મરચું","ਹਰੀ ਮਿਰਚ","பச்சை மிளகாய்","పచ్చి మిర్చి","ಹಸಿರು ಮೆಣಸಿನಕಾಯಿ","പച്ചമുളക്","ہری مرچ"]}),
  p("raisins","Raisins","raisin","Fresh Mills","Dry Fruits & Nuts","100 g","g",45,9,["healthy"],{photoSheet:1,aliases:["raisin","raisins","kishmish","किशमिश"]}),
  p("pistachios","Pistachios","pistachio","Fresh Mills","Dry Fruits & Nuts","100 g","g",140,10,["healthy","protein"],{photoSheet:1,aliases:["pistachio","pistachios","pista","पिस्ता"]}),
  p("walnuts","Walnuts","walnut","Fresh Mills","Dry Fruits & Nuts","100 g","g",130,11,["healthy"],{photoSheet:1,aliases:["walnut","walnuts","akhrot","अखरोट"]}),
  p("peanuts","Peanuts","peanut","Fresh Mills","Dry Fruits & Nuts","500 g","g",70,12,["protein"],{photoSheet:1,aliases:["peanut","peanuts","moongfali","mungfali","मूंगफली"]}),
  p("dates","Dates","date","Fresh Mills","Dry Fruits & Nuts","500 g","g",140,13,["healthy"],{photoSheet:1,aliases:["date","dates","khajur","खजूर"]}),
  p("sesame","Sesame Seeds","sesame","Fresh Mills","Spices","200 g","g",50,14,["seeds"],{photoSheet:1,aliases:["sesame","sesame seed","sesame seeds","til","तिल"]}),
  p("cumin","Cumin Seeds","cumin","Fresh Mills","Spices","100 g","g",45,15,["seeds"],{photoSheet:1,aliases:["cumin","cumin seed","cumin seeds","jeera","जीरा"]}),
  p("fenugreek","Fenugreek","fenugreek","Fresh","Produce","1 bunch","bunch",25,16,["fresh","herb"],{photoSheet:1,aliases:["fenugreek","methi","मेथी"]})
];

const categoryMap:Record<string,Category>={atta:"Grains & Flours",maida:"Grains & Flours",besan:"Grains & Flours",rice:"Grains & Flours",bajra:"Grains & Flours",coriander:"Produce",milk:"Dairy",egg:"Dairy",bread:"Bakery",sugar:"Cooking Essentials",salt:"Cooking Essentials",apple:"Produce",banana:"Produce",orange:"Produce",mango:"Produce",tomato:"Produce",onion:"Produce",spinach:"Produce",potato:"Produce",water:"Beverages",toothpaste:"Personal Care",toothbrush:"Personal Care",chips:"Snacks","cooking oil":"Cooking Essentials"};
export const categorize=(name:string):Category=>catalog.find(p=>p.normalizedName===name)?.category??categoryMap[name]??"Other Food";
